### ISSUE TITLE
Show input string

### ISSUE THREAD

**Issue by yashpalgoyal1304** [JuanPotato/unicode_bot#13]
Thanks a lot for the awesome bot. 

### What
It will be great if the input string is shown too. Suggestions' Rough sample shown below:  

1. Whole input as a parah in the starting before the codes  
![Telegram_6urTSTtLDz](https://user-images.githubusercontent.com/19423063/112752334-38a20f80-8ff0-11eb-8cf7-4792a0315687.png)
2. Individual Characters before each line (my preferred)  
![Telegram_D46xnAIjkC](https://user-images.githubusercontent.com/19423063/112752338-3dff5a00-8ff0-11eb-86e2-99a69b56c1b0.png)

Current o/p: 
![Telegram_6urTSTtLDz1](https://user-images.githubusercontent.com/19423063/112752271-c92c2000-8fef-11eb-92a6-9f533a60766e.png)

### Further Thoughts
- If this seems like it will be disliked, then it may be made adjustable in bot settings. I am assuming that bots can have settings in tg.
- Scope for extension  
Later in time, it can be further extended to show the input command - in case that modifies the input. Thinking about those planned commands. But it can be ignored for the time being.

**Comment by JuanPotato** [comment]
I don't like the idea very much because of invisible characters or other characters that won't show up well. It would also make the list of characters not be aligned. However I do see how it would be nice. I think I would add this as a command. Currently busy with uni and don't have time for that.

The settings idea is also pretty neat. Later on, any commands the bot has could be modified in settings to be the default behaviour of a user wants. But for now it's just the basic bot. I'll leave this issue open as a feature request

**Comment by yashpalgoyal1304** [comment]
hi, thanks for reply. All the best with uni. 👍 \
Yeah, list of characters wont be aligned in the second suggestion. Any negative point for giving the parah view in the starting (suggestion 1) ??

P.S. i have forgotten what i meant with "show the input command" lol. I thought i wrote it by referring the [readme](https://github.com/JuanPotato/unicode_bot) but it doesnt seem so either 😅 . Could u understand that??

**Comment by JuanPotato** [comment]
> Yeah, list of characters wont be aligned in the second suggestion. Any negative point for giving the parah view in the starting (suggestion 1) ??

Doing that for each character would make the message much taller with just lines of mostly whitespace which I don't like. Maybe for one character it would be fine, but for a whole message I don't think it would look nice.

> P.S. i have forgotten what i meant with "show the input command" lol. I thought i wrote it by referring the readme but it doesnt seem so either sweat_smile . Could u understand that??

Maybe you meant that the bot would write the whole message at the top before mentioning each character? I'm not sure either

**Comment by yashpalgoyal1304** [comment]
adding a reference i found: 
- the rest of it seems very similar to ur bot's output though.
- it has 2 types 
    - for single characters, it shows in 2nd style (in desc)
    - for multi characters, it shows in first style
- https://t.me/AnimatedEmojis  \
<br/>![Animated_Emojis_channel_xO3d1zJHiL](https://user-images.githubusercontent.com/19423063/131604082-80c519a4-08c7-458c-aa66-9cf7f80ae441.png)

**Comment by yashpalgoyal1304** [comment]
Refer: on [@inlatexbot](https://t.me/inlatexbot)

* `/setcodeincaptionon` : "add raw code to the caption
* `/setcodeincaptionoff` : "no raw code in the caption"

note:
* I totally understand that that is for code - visible characters, and the situation with unicode bot is not same.
* so, i am just saying this for records

**Comment by yashpalgoyal1304** [comment]
closing issue as i no longer interact that much anymore with deeper levels of telegram. feel free to reopen
